[[main]]
  name = "Programs"
  url = "/programs/"
  weight = 20
  identifier = "programs"
  hasChildren = true

# [[main]]
#   name = "Band Camp"
#   url = "/bandcamp/"
#   indentifier = "bandcamp"
#   weight = 35

[[main]]
  name = "Calendar"
  url = "/calendar/"
  weight = 30

[[main]]
  name = "Photos"
  url = "/photos/"
  weight = 40

[[main]]
  name = "News"
  url = "/news/"
  weight = 45

[[main]]
  name = "Resources"
  url = "/res/"
  weight = 50
  identifier = "resources"
  hasChildren = true

[[main]]
  name = "Support"
  url = "/support/"
  weight = 60

[[main]]
  name = "Recognition"
  url = "/recognition/"
  weight = 70

[[main]]
  name = "Alumni"
  url = "/alumni/"
  weight = 80

[[main]]
  name = "FAQ"
  url = "/faq/"
  weight = 90

[[main]]
  name = "Contact"
  url = "/contact/"
  weight = 100

# Programs submenu items
[[main]]
  name = "Marching Band"
  url = "/programs/marching-band/"
  weight = 10
  parent = "programs"

[[main]]
  name = "Concert Band"
  url = "/programs/concert-band/"
  weight = 20
  parent = "programs"

[[main]]
  name = "Jazz Band"
  url = "/programs/jazz-band/"
  weight = 30
  parent = "programs"

[[main]]
  name = "Wind Ensemble"
  url = "/programs/wind-ensemble/"
  weight = 40
  parent = "programs"

[[main]]
  name = "Winter Guard"
  url = "/programs/winter-guard/"
  weight = 50
  parent = "programs"

[[main]]
  name = "Middle School"
  url = "/programs/middle-school/"
  weight = 60
  parent = "programs"

# Resources submenu items
[[main]]
  name = "Band Handbook"
  url = "/res/handbook/"
  weight = 10
  parent = "resources"

[[main]]
  name = "Forms"
  url = "/res/forms/"
  weight = 20
  parent = "resources"

[[main]]
  name = "Practice Tools"
  url = "/res/practice-tools/"
  weight = 30
  parent = "resources"

[[main]]
  name = "Private Lessons"
  url = "/res/private-lessons/"
  weight = 40
  parent = "resources"

  [[main]]
  name = "Presentations"
  url = "/res/presentations/"
  weight = 50
  parent = "resources"

