baseURL = "/"
title = "Nordonia Hills Bands"
theme = "ananke"
languageCode = "en-us"

[params]
author = "Nordonia Bands"
site_logo = "/images/main/Nordonia_Bands_Logo_long.png"
favicon = "/images/main/NordoniaBand_logo.jpeg"
description = "Home of the Nordonia Hills Band Programs"
recent_posts_number = 3
cover_dimming_class = "bg-dark-green o-80"
background_color_class = "bg-dark-green"
featured_image_class = "cover bg-center"
