baseURL = "/"
title = "Nordonia Hills Bands"
theme = "ananke"
languageCode = "en-us"

[params]
author = "Nordonia Bands"
site_logo = ""
description = "Home of the Nordonia Hills Band Programs"
recent_posts_number = 3
